pages:
  image: node
  before_script:
    - pwd
  script:
    - cd angular-website
    - npm --version
    - date
    - yarn install
    - date
    - yarn run ng build --aot=true --prod --build-optimizer --verbose --progress=true --delete-output-path --extract-licenses --subresource-integrity --stats-json --output-path=public
    - date
    - du -sh public/
    - mv public ../public
    - ls -a
    - pwd
    - cd ..
    - ls -a
    - pwd
  artifacts:
    paths:
      - public

test:mypages:
  image: trion/ng-cli-karma
  script:
    - cd angular-website
    - pwd 
    - ls -a
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng e2e